# Generated by Django 4.1.7 on 2023-06-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0009_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYP_App.course')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYP_App.staff')),
            ],
        ),
    ]
