# Generated by Django 4.1.7 on 2023-06-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0012_alter_staff_subject_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-06-26'),
            preserve_default=False,
        ),
    ]
