# Generated by Django 4.1.7 on 2023-06-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0018_alter_result_created_at_alter_result_updated_at'),
    ]

    operations = [
    ]
