# Generated by Django 4.1.7 on 2023-06-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0020_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_year',
            field=models.IntegerField(),
        ),
    ]
