# Generated by Django 4.1.7 on 2023-06-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0021_alter_class_class_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYP_App.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYP_App.student')),
            ],
        ),
    ]
