# Generated by Django 4.1.7 on 2023-06-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0023_remove_class_class_year_class_session_year_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYP_App.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYP_App.course')),
            ],
        ),
    ]
