# Generated by Django 4.1.7 on 2023-07-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0024_class_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session_year_id',
        ),
    ]
