# Generated by Django 4.1.7 on 2023-07-02 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0026_staff_subject_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='session_year_id',
        ),
        migrations.AlterField(
            model_name='class',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FYP_App.session_year'),
        ),
    ]
