# Generated by Django 4.1.7 on 2023-07-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0027_remove_class_session_year_id_alter_class_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_year',
            name='session',
            field=models.CharField(max_length=4),
        ),
    ]
