# Generated by Django 4.1.7 on 2023-07-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0028_alter_session_year_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_subject',
            name='class_name',
        ),
    ]
