# Generated by Django 4.1.7 on 2023-07-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_App', '0030_alter_student_created_at_alter_student_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.IntegerField(),
        ),
    ]
